export type { MyObject, ParamsProps } from "./tmdb";
export { fetchMovie } from "./fetchMovie";
export { fetchMovieDetails } from "./fetchMovieDetails";
export { fetchMovieCredits } from "./fetchMovieCredits";
export { fetchMovieTrailer } from "./fetchMovieTrailer";
export { fetchMovieList } from "./fetchMovieList";
export { fetchPerson } from "./fetchPerson";
export { fetchPersonMovieCredits } from "./fetchPersonMovieCredits";
export { fetchGenres } from "./fetchGenres";
export { fetchMoviesWithGenre } from "./fetchMoviesWithGenre";
