import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import NavLinks from "@components/Navbar/NavLinks";
import Header from "@components/Header/Header";
import Footer from "@components/Footer/Footer";
import GoToTop from "./components/GoToTop/GoToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MovieTrip",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full`}>
        <Header />
        <NavLinks />
        {children}
        <GoToTop />
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
