import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PreventZoom from "./PreventZoom";
import { Analytics } from "@vercel/analytics/react";
import NavLinks from "@components/Navbar/NavLinks";
import Header from "@components/Header/Header";
import Footer from "@components/Footer/Footer";
import GoToTop from "./components/GoToTop/GoToTop";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MovieTrip",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${inter.className} w-full`}>
        <PreventZoom />
        <Header />
        <NavLinks />
        {children}
        <GoToTop />
        <Footer />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
